### ISSUE TITLE
Continue Maintaining This Extension

### ISSUE THREAD

**Issue by infohash** [zamzterz/Flask-pyoidc#145]
@zamzterz 

There aren't many maintained options available in Python to use OIDC. This extension works well for Flask and I don't want it to reach abandonment. I would like you to continue maintaining this extension so that nobody feels discouraged to use it. I have plans to improve the extension and with your attention, I can start working on it once again. As you are often active on Git, I would like you to give fraction of your attention to this repo as well.

Cheers

**Comment by zamzterz** [comment]
Hi @infohash,

Apologies for my slow response, I've been fully occupied with other work.

I still do not have much time to dedicate to this project so any maintenance will be very sporadic (but hopefully a bit more than the last couple of months).
However, I don't think that should discourage use of this extension - contributed bug fixes (in the form of PRs) will be prioritised going forward, but as the extension supports most of the commonly used parts of OpenID Connect the addition of features will not be prioritised (due to the lack of time on my part).

**Comment by infohash** [comment]
I have few more things in the pipeline before the extension can be put in the maintenance mode.

1. Feature to verify JWT access token in memory instead of using token introspection which is only needed for opaque access token. It was a mistake to use token introspection for JWT as it defeats the purpose of using JWT in the first place. It will be minor fix to change this.
2. Refactoring tests.
3. Documentation overhaul - I will move the documentation to mkdocs-material UI for better readability and examples.
4. Google-style docstring - This is easier to write and more readable. I have a good experience with it.
5. Type hinting and static type checker.

There is no timeline so you can review whenever you have time. Better if you consider hiring a maintainer 😁.

**Comment by zamzterz** [comment]
All sounds like very good things to fix and I'll be happy to review the PRs for it. 👍
