### ISSUE TITLE
How to change redirecturi for static client registration?

### ISSUE THREAD

**Issue by Suven10** [zamzterz/Flask-pyoidc#40]
I want to authenticate with google cloud application. I have created an application in google cloud and created client_credentials as well. my authentication works perfectly only when I set redirect_uri in google application client credentials to <application_url>/redirect_uri. I want to change the redirect uri to some other. I'm facing issues to change the redirect_uri from my application. How to achieve this?

**Comment by zamzterz** [comment]
That is currently not possible. As you noticed, and as [described in the documentation](https://github.com/zamzterz/Flask-pyoidc#static-client-registration), you have to use ` <application_url>/redirect_uri`.

What's the use case for changing the value? Flask-pyoidc handles all requests reaching the redirect_uri internally, that's why the value is not customizable.

**Comment by Suven10** [comment]
Ok thanks. I have another issue where I neee to use pyoidc’s own identity server provider and google as authentication provider for login. I found the repository of pyoidc in github but when I tried to run the example and see how it works I couldn’t do it. I’m using windows. It says fcntl module is not found. How to configure both google and local identity provider of pyoidc together in my authentication server?

**Comment by zamzterz** [comment]
That Windows issue should be reported directly in the [pyoidc repository](https://github.com/OpenIDC/pyoidc/issues).

If you want to use multiple providers with Flask-pyoidc, that is [documented in the README](https://github.com/zamzterz/Flask-pyoidc#using-multiple-providers). 🙂
